### PR TITLE
fix Default scope

### PR DESCRIPTION
**Pull request by fmnoise**

### CODE REVIEW

**Comment by kukareka** [comment]
Looks good despite I don't know what it does :trollface:

**Comment by sevaorlov** [comment]
can you also write tests and open PR to acts_as_paranoid?

**Comment by fmnoise** [comment]
actually I don't know how to test it, we opened it just because it works bad together with database cleaner when different database adapters are used

**Comment by fmnoise** [comment]
opened https://github.com/ActsAsParanoid/acts_as_paranoid/pull/49 and raised https://github.com/ActsAsParanoid/acts_as_paranoid/issues/50

**Pull request closed without merging**
